version: '2.4'
services:
    backend:
        container_name: backend
        build: .
        image: ghcr.io/chicky0/int222-backend:latest
        volumes:
            - /home/wongnokproject/Back-End/public:/tmp
        ports:
            - "3000:80"
        restart: always
networks:
  default:
    external:
      name: wongnokproject