version: '2.2'
services:
    backend:
        container_name: backend
        build: .
        image: backend
        volumes:
            - /home/wongnokproject/Back-End/public:/tmp
        ports:
            - "3000:3000"
        restart: always