name: deploy-backend-wongnok
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@main
#   deploy:
#     needs: build
#     runs-on: ubuntu-20.04
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@main
#       - name: pull images and deploy
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.SSH_HOST }}
#           username: ${{ secrets.SSH_USERNAME }}
#           password: ${{ secrets.SSH_PASSWORD }}
#           port: ${{ secrets.SSH_PORT }}
#           script: |
#             cd int222-backend
#             git pull origin main
#             sudo docker rm -f backend
#             sudo docker rmi ghcr.io/chicky0/int222-backend
#             sudo docker pull ghcr.io/chicky0/int222-backend:latest
#             sudo docker-compose up -d